# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_table', '0014_remove_fundamentalproducttype_name2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('particular', models.TextField(blank=True, null=True)),
                ('payment_option', models.CharField(choices=[('cash', 'Payment By Cash'), ('bank', 'Payment By Bank')], help_text='Select Payment Option: ', max_length=30)),
                ('transection_no', models.CharField(max_length=100, unique=True)),
                ('amount', models.IntegerField(default=0)),
                ('customer_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.Customer', to_field='code')),
                ('deport_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.Deport', to_field='code')),
            ],
        ),
    ]
