# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0014_remove_fundamentalproducttype_name2'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transection_no', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('memo_no', models.CharField(max_length=100, unique=True)),
                ('amount', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('deport_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.Deport', to_field='code')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.FPItem')),
            ],
        ),
    ]
