# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0015_expensecriteria'),
        ('sales', '0002_sell'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('serial_no', models.CharField(max_length=100, unique=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('deport_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.Deport', to_field='code')),
                ('expense_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.ExpenseCriteria', to_field='code', verbose_name='Expense Specification')),
            ],
        ),
    ]
