# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_expensedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensedetail',
            name='serial_no',
        ),
    ]
