# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_expensedetail_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensedetail',
            name='invoice_no',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
