# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0018_auto_20161221_1719'),
        ('sales', '0005_expensedetail_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='account_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.BankAccount', to_field='code', verbose_name='A/C No:'),
        ),
        migrations.AddField(
            model_name='credit',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.Bank', to_field='code', verbose_name='Select Bank'),
        ),
    ]
