# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 17:30
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20161221_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='account_no',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='bank', chained_model_field='bank', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.BankAccount', verbose_name='A/C No:'),
        ),
    ]
