# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20161221_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='customer_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.Customer', to_field='code', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='deport_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.Deport', to_field='code', verbose_name='Deport'),
        ),
    ]
