# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0018_auto_20161221_1719'),
        ('sales', '0008_auto_20161222_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('commission', models.FloatField(default=1)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.FPItem')),
            ],
        ),
        migrations.RemoveField(
            model_name='sell',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='quantity',
        ),
        migrations.AddField(
            model_name='sell',
            name='customer_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_table.Customer', to_field='code'),
            preserve_default=False,
        ),
    ]
