# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20161222_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='selldetailinfo',
            name='sell',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.Sell'),
            preserve_default=False,
        ),
    ]
