# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0018_auto_20161221_1719'),
        ('sales', '0010_selldetailinfo_sell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selldetailinfo',
            name='product_id',
        ),
        migrations.AddField(
            model_name='selldetailinfo',
            name='finished_product_item',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='lower_category_type', chained_model_field='lower_category_type', default=1, on_delete=django.db.models.deletion.CASCADE, to='master_table.FPItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selldetailinfo',
            name='fundamental_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_table.FundamentalProductType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selldetailinfo',
            name='lower_category_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='middle_category_type', chained_model_field='middle_category_type', default=1, on_delete=django.db.models.deletion.CASCADE, to='master_table.FPLowerCat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selldetailinfo',
            name='middle_category_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='fundamental_type', chained_model_field='fundamental_type', default=1, on_delete=django.db.models.deletion.CASCADE, to='master_table.FPMiddleCat'),
            preserve_default=False,
        ),
    ]
