# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0018_auto_20161221_1719'),
        ('sales', '0011_auto_20161222_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeportOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deport_operation', models.CharField(choices=[('new', 'New Arrival'), ('received_from_other_deport', 'Received From Other Deport'), ('sales_return', 'Sales Return'), ('factory_return', 'Factory Return')], help_text='Select Deport Operation: ', max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.Customer', to_field='code', verbose_name='Party')),
                ('deport_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.Deport', to_field='code')),
                ('finished_product_item', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='lower_category_type', chained_model_field='lower_category_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.FPItem')),
                ('fundamental_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.FundamentalProductType')),
                ('lower_category_type', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='middle_category_type', chained_model_field='middle_category_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.FPLowerCat')),
                ('middle_category_type', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='fundamental_type', chained_model_field='fundamental_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.FPMiddleCat')),
            ],
        ),
    ]
