# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0018_auto_20161221_1719'),
        ('sales', '0012_deportoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportoperation',
            name='deport_from_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deport_from_code', to='master_table.Deport', to_field='code', verbose_name='Deport From'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deportoperation',
            name='deport_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deport_code', to='master_table.Deport', to_field='code'),
        ),
    ]
