# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_auto_20161222_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deportoperation',
            name='lower_category_type',
        ),
        migrations.RemoveField(
            model_name='deportoperation',
            name='middle_category_type',
        ),
    ]
