# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0018_auto_20161221_1719'),
        ('sales', '0015_auto_20161222_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportoperation',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='master_table.FPItem'),
        ),
    ]
