# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_deportoperation_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportoperation',
            name='customer_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.Customer', to_field='code', verbose_name='Party'),
        ),
        migrations.AlterField(
            model_name='deportoperation',
            name='deport_from_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deport_from_code', to='master_table.Deport', to_field='code', verbose_name='Deport From'),
        ),
        migrations.AlterField(
            model_name='deportoperation',
            name='finished_product_item',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='lower_category_type', chained_model_field='lower_category_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.FPItem'),
        ),
        migrations.AlterField(
            model_name='deportoperation',
            name='lower_category_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='middle_category_type', chained_model_field='middle_category_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.FPLowerCat'),
        ),
        migrations.AlterField(
            model_name='deportoperation',
            name='middle_category_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='fundamental_type', chained_model_field='fundamental_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.FPMiddleCat'),
        ),
    ]
