# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_auto_20161222_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='deport_code_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
