# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_auto_20161222_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selldetailinfo',
            name='finished_product_item',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='lower_category_type', chained_model_field='lower_category_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.FPItem', verbose_name='Finished Product'),
        ),
        migrations.AlterField(
            model_name='selldetailinfo',
            name='fundamental_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.FundamentalProductType', verbose_name='Main Cat'),
        ),
        migrations.AlterField(
            model_name='selldetailinfo',
            name='lower_category_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='middle_category_type', chained_model_field='middle_category_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.FPLowerCat', verbose_name='Lower Cat'),
        ),
        migrations.AlterField(
            model_name='selldetailinfo',
            name='middle_category_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='fundamental_type', chained_model_field='fundamental_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.FPMiddleCat', verbose_name='Mid Cat'),
        ),
    ]
