# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 18:46
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_auto_20161222_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selldetailinfo',
            name='finished_product_item',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='lower_category_type', chained_model_field='lower_category_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.FPItem', verbose_name='Product'),
        ),
    ]
