# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_auto_20161223_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='selldetailinfo',
            name='product_code_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=''),
        ),
    ]
