# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_selldetailinfo_product_code_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='selldetailinfo',
            name='net_total_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Net Total'),
        ),
        migrations.AddField(
            model_name='selldetailinfo',
            name='total_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Total'),
        ),
    ]
