# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_auto_20161223_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selldetailinfo',
            name='net_total_text',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='Net Total'),
        ),
        migrations.AlterField(
            model_name='selldetailinfo',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='selldetailinfo',
            name='rate',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='selldetailinfo',
            name='total_text',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='Total'),
        ),
    ]
