# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_auto_20161223_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='grand_total_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grand Total'),
        ),
    ]
