# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_auto_20161223_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedetail',
            name='deport_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.Deport'),
        ),
        migrations.AlterField(
            model_name='expensedetail',
            name='expense_criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.ExpenseCriteria', verbose_name='Expense Specification'),
        ),
    ]
