# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0067_auto_20170106_1325'),
        ('sales', '0030_auto_20170113_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensedetail',
            name='deport_many',
            field=models.ManyToManyField(blank=True, related_name='ed_deport_m', to='master_table.Deport'),
        ),
        migrations.AddField(
            model_name='expensedetail',
            name='expense_criteria_many',
            field=models.ManyToManyField(related_name='ed_exc_m', to='master_table.ExpenseCriteria', verbose_name='Expense Specification'),
        ),
        migrations.AlterField(
            model_name='expensedetail',
            name='deport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.Deport'),
        ),
    ]
