# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_auto_20170113_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensedetail',
            name='deport_many',
        ),
        migrations.RemoveField(
            model_name='expensedetail',
            name='expense_criteria_many',
        ),
    ]
