# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0067_auto_20170106_1325'),
        ('sales', '0033_auto_20170113_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='deport_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='deport_code_text',
        ),
        migrations.AddField(
            model_name='payment',
            name='deport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_table.Deport', verbose_name='Deport'),
            preserve_default=False,
        ),
    ]
