# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0067_auto_20170106_1325'),
        ('sales', '0035_auto_20170113_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deportoperation',
            name='finished_product_item',
        ),
        migrations.RemoveField(
            model_name='deportoperation',
            name='product_id',
        ),
        migrations.AddField(
            model_name='deportoperation',
            name='fp_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.FPItem'),
        ),
        migrations.AddField(
            model_name='deportoperation',
            name='fp_item_chained',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='lower_category_type', chained_model_field='lower_category_type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_fp_chained', to='master_table.FPItem'),
        ),
        migrations.AddField(
            model_name='deportoperation',
            name='fp_item_many',
            field=models.ManyToManyField(blank=True, null=True, related_name='sales_fp_many', to='master_table.FPItem'),
        ),
    ]
