# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0037_auto_20170113_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportoperation',
            name='customer',
            field=models.ManyToManyField(blank=True, to='master_table.Customer', verbose_name='Customer'),
        ),
    ]
