# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_auto_20170113_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportoperation',
            name='fp_item_many',
            field=models.ManyToManyField(blank=True, related_name='sales_fp_many', to='master_table.FPItem'),
        ),
    ]
