# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0067_auto_20170106_1325'),
        ('sales', '0039_auto_20170113_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='customer_code',
        ),
        migrations.AddField(
            model_name='sell',
            name='customer',
            field=models.ManyToManyField(to='master_table.Customer'),
        ),
    ]
