# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0040_auto_20170113_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='memo_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sell',
            name='transection_no',
            field=models.CharField(max_length=100),
        ),
    ]
