# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0041_auto_20170113_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='grand_total_text',
            field=models.FloatField(default=0, verbose_name='Grand Total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sell',
            name='net_total_text',
            field=models.FloatField(default=0, verbose_name='Net Total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sell',
            name='total_commission_text',
            field=models.FloatField(default=0, verbose_name='Total Commission'),
            preserve_default=False,
        ),
    ]
