# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0042_auto_20170116_0319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell',
            old_name='grand_total_text',
            new_name='grand_total',
        ),
        migrations.RenameField(
            model_name='sell',
            old_name='net_total_text',
            new_name='net_total',
        ),
        migrations.RenameField(
            model_name='sell',
            old_name='total_commission_text',
            new_name='total_commission',
        ),
    ]
