# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0043_auto_20170116_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selldetailinfo',
            name='net_total_text',
        ),
        migrations.RemoveField(
            model_name='selldetailinfo',
            name='total_text',
        ),
        migrations.AddField(
            model_name='selldetailinfo',
            name='net_total',
            field=models.FloatField(default=0, verbose_name='Net Total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='selldetailinfo',
            name='commission',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='selldetailinfo',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
