# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0045_remove_selldetailinfo_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='selldetailinfo',
            name='commission',
            field=models.FloatField(default=0),
        ),
    ]
