# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0046_selldetailinfo_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='selldetailinfo',
            name='total2',
            field=models.FloatField(default=0, verbose_name='Total'),
        ),
    ]
