# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0049_selldetailinfo_total2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selldetailinfo',
            name='total2',
        ),
    ]
