# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0050_remove_selldetailinfo_total2'),
    ]

    operations = [
        migrations.AddField(
            model_name='selldetailinfo',
            name='total',
            field=models.FloatField(default=0, verbose_name='Grand Total'),
        ),
    ]
