# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0051_selldetailinfo_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selldetailinfo',
            name='total',
            field=models.FloatField(default=0, verbose_name='Total'),
        ),
    ]
