# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 06:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0052_auto_20170116_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='selldetailinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 16, 6, 11, 42, 228750, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
    ]
