# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0053_selldetailinfo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selldetailinfo',
            name='date',
        ),
    ]
