# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0069_auto_20170116_0207'),
        ('sales', '0054_remove_selldetailinfo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='deport_code',
        ),
        migrations.AddField(
            model_name='sell',
            name='deport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_table.Deport'),
            preserve_default=False,
        ),
    ]
