# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0055_auto_20170116_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportoperation',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
