# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0057_auto_20170116_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportoperation',
            name='transection_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Sell'),
        ),
    ]
