# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0059_deportoperation_return_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sell',
            options={'verbose_name': 'Sale ', 'verbose_name_plural': 'Sales'},
        ),
    ]
