# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0060_auto_20170122_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportoperation',
            name='deport_from_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deport_from_code', to='master_table.Deport', to_field='code', verbose_name='Depot From'),
        ),
        migrations.AlterField(
            model_name='expensedetail',
            name='deport',
            field=models.ManyToManyField(to='master_table.Deport', verbose_name='Depot'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='deport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.Deport', verbose_name='Depot'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='deport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.Deport', verbose_name='Depot'),
        ),
    ]
