# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0061_auto_20170122_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportoperation',
            name='return_rate',
            field=models.FloatField(),
        ),
    ]
