# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0064_auto_20170122_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selldetailinfo',
            name='commission',
            field=models.FloatField(default=0, verbose_name='Commission Rate'),
        ),
    ]
