# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0065_auto_20170126_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='serial_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transection_no',
            field=models.CharField(max_length=100),
        ),
    ]
