# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0068_auto_20170126_0650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deportoperation',
            options={'verbose_name': 'Depot Operation', 'verbose_name_plural': 'Depot Operation'},
        ),
        migrations.AlterField(
            model_name='deportoperation',
            name='deport_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deport_code', to='master_table.Deport', to_field='code', verbose_name='Depot Code'),
        ),
        migrations.AlterField(
            model_name='deportoperation',
            name='deport_operation',
            field=models.CharField(choices=[('new', 'New Arrival'), ('received_from_other_deport', 'Received From Other Depot'), ('sales_return', 'Sales Return'), ('factory_return', 'Factory Return')], help_text='Select Deport Operation: ', max_length=30, verbose_name='Depot Operation'),
        ),
    ]
