# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0069_auto_20170127_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='transection_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
