# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0071_auto_20170221_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deportoperation',
            name='transection_no',
        ),
        migrations.AddField(
            model_name='deportoperation',
            name='memo_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Sell', to_field='memo_no'),
        ),
    ]
