# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0073_auto_20170221_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportoperation',
            name='chalan_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
