# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0074_deportoperation_chalan_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportoperation',
            name='transection_no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
