# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0077_auto_20170221_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='selldetailinfo',
            name='commission_amount',
            field=models.FloatField(default=0, verbose_name='Commission Amount'),
        ),
    ]
