# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0080_auto_20170221_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportoperation',
            name='transection_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='Transaction No'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transection_no',
            field=models.CharField(max_length=100, verbose_name='Transaction No'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='transection_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='Transaction No'),
        ),
    ]
