# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CompoundProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompoundProductItemEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_amount', models.FloatField()),
                ('compound_production_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.CompoundProductItem')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FPLowerCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Finished Product Item Lower Categories',
                'verbose_name': 'Finished Product Item Lower Category',
            },
        ),
        migrations.CreateModel(
            name='FPMiddleCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Finished Product Item Middle Categories',
                'verbose_name': 'Finished Product Item Middle Category',
            },
        ),
        migrations.CreateModel(
            name='FundamentalProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RawItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('fundamental_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.FundamentalProductType')),
            ],
        ),
        migrations.CreateModel(
            name='RILowerCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('fundamental_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.FundamentalProductType')),
            ],
            options={
                'verbose_name_plural': 'Raw Item Lower Categories',
                'verbose_name': 'Raw Item Lower Category',
            },
        ),
        migrations.CreateModel(
            name='RIMiddleCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('fundamental_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.FundamentalProductType')),
            ],
            options={
                'verbose_name_plural': 'Raw Item Middle Categories',
                'verbose_name': 'Raw Item Middle Category',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone1', models.CharField(blank=True, max_length=30, null=True)),
                ('phone2', models.CharField(blank=True, max_length=30, null=True)),
                ('phone3', models.CharField(blank=True, max_length=30, null=True)),
                ('phone4', models.CharField(blank=True, max_length=30, null=True)),
                ('phone5', models.CharField(blank=True, max_length=30, null=True)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('edit_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='rilowercat',
            name='middle_category_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.RIMiddleCat'),
        ),
        migrations.AddField(
            model_name='rawitem',
            name='lower_category_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.RILowerCat'),
        ),
        migrations.AddField(
            model_name='rawitem',
            name='middle_category_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.RIMiddleCat'),
        ),
        migrations.AddField(
            model_name='fpmiddlecat',
            name='fundamental_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.FundamentalProductType'),
        ),
        migrations.AddField(
            model_name='fplowercat',
            name='fundamental_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.FundamentalProductType'),
        ),
        migrations.AddField(
            model_name='fplowercat',
            name='middle_category_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='fundamental_type', chained_model_field='fundamental_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.FPMiddleCat'),
        ),
        migrations.AddField(
            model_name='finishedproductitem',
            name='fundamental_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.FundamentalProductType'),
        ),
        migrations.AddField(
            model_name='finishedproductitem',
            name='lower_category_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='middle_category_type', chained_model_field='middle_category_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.FPLowerCat'),
        ),
        migrations.AddField(
            model_name='finishedproductitem',
            name='middle_category_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='fundamental_type', chained_model_field='fundamental_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.FPMiddleCat'),
        ),
        migrations.AddField(
            model_name='compoundproductitementry',
            name='finished_production_item',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='lower_category_type', chained_model_field='lower_category_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.FinishedProductItem'),
        ),
        migrations.AddField(
            model_name='compoundproductitementry',
            name='fundamental_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.FundamentalProductType'),
        ),
        migrations.AddField(
            model_name='compoundproductitementry',
            name='lower_category_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='middle_category_type', chained_model_field='middle_category_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.FPLowerCat'),
        ),
        migrations.AddField(
            model_name='compoundproductitementry',
            name='middle_category_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='fundamental_type', chained_model_field='fundamental_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.FPMiddleCat'),
        ),
        migrations.AddField(
            model_name='compoundproductitem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.FundamentalProductType'),
        ),
    ]
