# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone1', models.CharField(max_length=30)),
                ('phone2', models.CharField(max_length=30)),
                ('phone3', models.CharField(max_length=30)),
                ('phone4', models.CharField(max_length=30)),
                ('phone5', models.CharField(max_length=30)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('edit_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
