# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suplier',
            name='phone1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='phone2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='phone3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='phone4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='phone5',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
