# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0002_compoundproductitem_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compoundproductitem',
            name='name2',
        ),
    ]
