# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0002_remove_fpitem_comment2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fpitem',
            options={'verbose_name': 'Finished Product Item ', 'verbose_name_plural': 'Finished Product Items'},
        ),
    ]
