# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0003_auto_20161125_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpitem',
            name='fp_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.FPItem', verbose_name='Select Compound Product'),
        ),
    ]
