# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0004_remove_compoundproductitementry_unit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='fundamental_product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_table.FundamentalProductType'),
            preserve_default=False,
        ),
    ]
