# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0004_auto_20161214_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpitem',
            name='is_compound_product',
            field=models.BooleanField(default=False),
        ),
    ]
