# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0005_shift_fundamental_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rilowercat',
            name='fundamental_type',
        ),
        migrations.RemoveField(
            model_name='rilowercat',
            name='middle_category_type',
        ),
        migrations.RemoveField(
            model_name='rimiddlecat',
            name='fundamental_type',
        ),
        migrations.RemoveField(
            model_name='rawitem',
            name='lower_category_type',
        ),
        migrations.RemoveField(
            model_name='rawitem',
            name='middle_category_type',
        ),
        migrations.DeleteModel(
            name='RILowerCat',
        ),
        migrations.DeleteModel(
            name='RIMiddleCat',
        ),
    ]
