# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0005_fpitem_is_compound_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fpitem',
            old_name='is_compound_product',
            new_name='is_cp',
        ),
    ]
