# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0006_auto_20161214_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpitem',
            name='is_cp',
            field=models.BooleanField(default=False, verbose_name='Is Compound Item'),
        ),
    ]
