# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0006_auto_20161121_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='fundamental_product_type',
            new_name='fundamental_type',
        ),
    ]
