# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0007_compoundproductionitem_compoundproductionitementry'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoundproductionitementry',
            name='unit_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
