# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0007_auto_20161121_1100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompoundProductItem',
            new_name='CPItem',
        ),
        migrations.RemoveField(
            model_name='compoundproductitementry',
            name='compound_production_item',
        ),
        migrations.RemoveField(
            model_name='compoundproductitementry',
            name='finished_production_item',
        ),
        migrations.RemoveField(
            model_name='compoundproductitementry',
            name='fundamental_type',
        ),
        migrations.RemoveField(
            model_name='compoundproductitementry',
            name='lower_category_type',
        ),
        migrations.RemoveField(
            model_name='compoundproductitementry',
            name='middle_category_type',
        ),
        migrations.DeleteModel(
            name='CompoundProductItemEntry',
        ),
    ]
