# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0008_auto_20161218_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deport',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
