# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0008_auto_20161121_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPItemEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.CPItem')),
                ('finished_production_item', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='lower_category_type', chained_model_field='lower_category_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.FinishedProductItem')),
                ('fundamental_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.FundamentalProductType')),
                ('lower_category_type', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='middle_category_type', chained_model_field='middle_category_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.FPLowerCat')),
                ('middle_category_type', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='fundamental_type', chained_model_field='fundamental_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.FPMiddleCat')),
            ],
        ),
    ]
