# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0008_compoundproductionitementry_unit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoundproductionitem',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawitem',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
