# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0009_cpitementry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpitem',
            options={'verbose_name': 'Compound Product Item', 'verbose_name_plural': 'Compound Product Items'},
        ),
        migrations.AddField(
            model_name='cpitementry',
            name='unit_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
