# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0010_shift2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift2',
            name='fundamental_type',
        ),
        migrations.DeleteModel(
            name='Shift2',
        ),
    ]
