# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0011_remove_cpitem_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
