# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0011_auto_20161219_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamentalproducttype',
            name='phone1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
