# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0012_fundamentalproducttype_phone1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundamentalproducttype',
            name='phone1',
        ),
        migrations.AddField(
            model_name='fundamentalproducttype',
            name='name2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
