# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0014_remove_fundamentalproducttype_name2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
