# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0016_auto_20161221_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='account_no',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_table.Bank', verbose_name='Select Bank'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Bank Account Number:'),
        ),
    ]
