# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0017_auto_20161221_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.Bank', to_field='code', verbose_name='Select Bank'),
        ),
    ]
