# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0018_auto_20161221_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='code',
        ),
    ]
