# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0020_suplier_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suplier',
            name='code',
            field=models.CharField(default='<function now at 0x7f1813c3e488>', max_length=30),
        ),
    ]
