# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0022_auto_20161223_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawitem',
            name='code',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
