# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0023_rawitem_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawitem',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
