# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0024_auto_20161223_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpitem',
            name='code',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
