# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0026_auto_20161223_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suplier',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='suplier',
            name='edit_time',
        ),
    ]
