# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0029_auto_20170103_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpmiddlecat',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Middle Category Name:'),
        ),
    ]
