# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0030_auto_20170103_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpitem',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Finished Product Name:'),
        ),
        migrations.AlterField(
            model_name='fplowercat',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Lower Category Name:'),
        ),
    ]
