# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0031_auto_20170103_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpitem',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='fpitem',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='fplowercat',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='fpmiddlecat',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='rawitem',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='comment',
        ),
    ]
