# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0032_auto_20170103_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='suplier',
            name='fundamental_type',
            field=models.ManyToManyField(to='master_table.FundamentalProductType'),
        ),
    ]
