# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0033_suplier_fundamental_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suplier',
            name='fundamental_type',
            field=models.ManyToManyField(blank=True, null=True, to='master_table.FundamentalProductType'),
        ),
    ]
