# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0035_auto_20170103_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='suplier',
            name='Customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_table.Customer'),
            preserve_default=False,
        ),
    ]
