# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0036_suplier_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suplier',
            name='Customer',
        ),
    ]
