# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0037_remove_suplier_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('address', models.TextField()),
                ('phone1', models.CharField(blank=True, max_length=30, null=True)),
                ('phone2', models.CharField(blank=True, max_length=30, null=True)),
                ('phone3', models.CharField(blank=True, max_length=30, null=True)),
                ('phone4', models.CharField(blank=True, max_length=30, null=True)),
                ('phone5', models.CharField(blank=True, max_length=30, null=True)),
                ('fundamental_type', models.ManyToManyField(to='master_table.FundamentalProductType')),
            ],
        ),
    ]
