# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0039_remove_suplier_fundamental_type'),
        ('mother_godown', '0007_auto_20170103_0842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suplier',
        ),
    ]
