# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0041_rimiddlecat'),
    ]

    operations = [
        migrations.CreateModel(
            name='RILowerCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Raw Item Lower Category Name:')),
                ('fundamental_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.FundamentalProductType')),
                ('middle_category_type', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='fundamental_type', chained_model_field='fundamental_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.RIMiddleCat')),
            ],
            options={
                'verbose_name': 'Raw Item  Lower Category',
                'verbose_name_plural': 'Raw Item Lower Categories',
            },
        ),
    ]
