# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 08:57
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0042_rilowercat'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawitem',
            name='lower_category_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='middle_category_type', chained_model_field='middle_category_type', default=1, on_delete=django.db.models.deletion.CASCADE, to='master_table.RILowerCat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawitem',
            name='middle_category_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='fundamental_type', chained_model_field='fundamental_type', default=1, on_delete=django.db.models.deletion.CASCADE, to='master_table.RIMiddleCat'),
            preserve_default=False,
        ),
    ]
