# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0043_auto_20170103_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fp', models.CharField(max_length=1, verbose_name='Finished Product Fundamental Type Code: ')),
            ],
        ),
    ]
