# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0044_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='ri',
            field=models.CharField(default=1, max_length=1, verbose_name='Raw Item Fundamental Type Code: '),
            preserve_default=False,
        ),
    ]
