# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0045_code_ri'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpmiddlecat',
            name='code',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
