# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0047_auto_20170103_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamentalproducttype',
            name='fp_code',
            field=models.CharField(default=1, max_length=1, verbose_name='Finished Product Code:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundamentalproducttype',
            name='ri_code',
            field=models.CharField(default=1, max_length=1, verbose_name='Raw Item Code:'),
            preserve_default=False,
        ),
    ]
