# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0048_auto_20170103_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundamentalproducttype',
            name='fp_code',
            field=models.CharField(max_length=1, unique=True, verbose_name='Finished Product Code:'),
        ),
        migrations.AlterField(
            model_name='fundamentalproducttype',
            name='ri_code',
            field=models.CharField(max_length=1, unique=True, verbose_name='Raw Item Code:'),
        ),
    ]
