# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0049_auto_20170103_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fpmiddlecat',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='fpmiddlecat',
            unique_together=set([('code',)]),
        ),
    ]
