# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0050_auto_20170103_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fpmiddlecat',
            options={'verbose_name': 'Finished Product Item Middle Category', 'verbose_name_plural': 'Finished Product Item Middle Categories'},
        ),
        migrations.AlterField(
            model_name='fpmiddlecat',
            name='code',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='fpmiddlecat',
            unique_together=set([]),
        ),
    ]
