# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0053_auto_20170105_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpitem',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
