# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0058_auto_20170105_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='rilowercat',
            name='code',
            field=models.CharField(default=1, max_length=1, unique=True),
            preserve_default=False,
        ),
    ]
