# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0059_rilowercat_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawitem',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
