# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0060_auto_20170105_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawitem',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
