# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0061_rawitem_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='fp',
        ),
        migrations.RemoveField(
            model_name='code',
            name='ri',
        ),
        migrations.AddField(
            model_name='code',
            name='Customer_code',
            field=models.CharField(default=1, max_length=3, verbose_name='Customer Code: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='code',
            name='bank_code',
            field=models.CharField(default=1, max_length=3, verbose_name='Customer Code: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='code',
            name='deport_code',
            field=models.CharField(default=1, max_length=3, verbose_name='Customer Code: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='code',
            name='supplier_code',
            field=models.CharField(default=1, max_length=3, verbose_name='Supplier Code: '),
            preserve_default=False,
        ),
    ]
