# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0064_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='bank_code',
            field=models.CharField(max_length=3, verbose_name='Bank Code: '),
        ),
        migrations.AlterField(
            model_name='code',
            name='deport_code',
            field=models.CharField(max_length=3, verbose_name='Deport Code: '),
        ),
    ]
