# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0066_auto_20170106_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='Customer_code',
            new_name='customer_code',
        ),
    ]
