# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0067_auto_20170106_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='deport_code',
            new_name='deport',
        ),
    ]
