# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0068_auto_20170116_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='deport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.Deport'),
        ),
    ]
