# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0069_auto_20170116_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpitem',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
    ]
