# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0070_fpitem_unit_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deport',
            options={'verbose_name': 'Depot', 'verbose_name_plural': 'Depotes'},
        ),
    ]
