# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0071_auto_20170122_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='deport_code',
            field=models.CharField(max_length=3, verbose_name='Depot Code: '),
        ),
        migrations.AlterField(
            model_name='customer',
            name='deport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.Deport', verbose_name='Depot'),
        ),
    ]
