# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_table', '0004_remove_compoundproductitementry_unit_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProductReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('finished_production_item', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='lower_category_type', chained_model_field='lower_category_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.FinishedProductItem')),
                ('fundamental_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.FundamentalProductType')),
                ('lower_category_type', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='middle_category_type', chained_model_field='middle_category_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.FPLowerCat')),
                ('middle_category_type', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='fundamental_type', chained_model_field='fundamental_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.FPMiddleCat')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.Shift')),
            ],
        ),
    ]
