# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProductReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('finished_production_item', smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, chained_field='lower_category_type', chained_model_field='lower_category_type', to='master_table.FPItem')),
                ('fundamental_type', models.ManyToManyField(to='master_table.FundamentalProductType')),
                ('lower_category_type', smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, chained_field='middle_category_type', chained_model_field='middle_category_type', to='master_table.FPLowerCat')),
                ('middle_category_type', smart_selects.db_fields.ChainedManyToManyField(chained_field='fundamental_type', chained_model_field='fundamental_type', to='master_table.FPMiddleCat')),
                ('shift', models.ManyToManyField(blank=True, to='master_table.Shift')),
            ],
        ),
    ]
