# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0004_remove_compoundproductitementry_unit_amount'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedproductreport',
            name='fundamental_type',
        ),
        migrations.AddField(
            model_name='finishedproductreport',
            name='fundamental_type',
            field=models.ManyToManyField(blank=True, to='master_table.FundamentalProductType'),
        ),
    ]
