# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedproductreport',
            name='finished_production_item',
        ),
        migrations.RemoveField(
            model_name='finishedproductreport',
            name='fundamental_type',
        ),
        migrations.RemoveField(
            model_name='finishedproductreport',
            name='lower_category_type',
        ),
        migrations.RemoveField(
            model_name='finishedproductreport',
            name='middle_category_type',
        ),
        migrations.RemoveField(
            model_name='finishedproductreport',
            name='shift',
        ),
        migrations.DeleteModel(
            name='FinishedProductReport',
        ),
    ]
