# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 10:25
from __future__ import unicode_literals

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0004_remove_compoundproductitementry_unit_amount'),
        ('report', '0002_auto_20161113_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedproductreport',
            name='middle_category_type',
        ),
        migrations.AddField(
            model_name='finishedproductreport',
            name='middle_category_type',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, chained_field='fundamental_type', chained_model_field='fundamental_type', to='master_table.FPMiddleCat'),
        ),
    ]
