# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_time',
            field=models.DateField(),
        ),
    ]
