# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0004_remove_compoundproductitementry_unit_amount'),
        ('report', '0005_auto_20161113_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedproductreport',
            name='shift',
        ),
        migrations.AddField(
            model_name='finishedproductreport',
            name='shift',
            field=models.ManyToManyField(blank=True, to='master_table.Shift'),
        ),
    ]
