# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0067_auto_20170106_1325'),
        ('report', '0005_report_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='FundamentalProductType',
            field=models.ManyToManyField(blank=True, to='master_table.FundamentalProductType'),
        ),
        migrations.AddField(
            model_name='report',
            name='fp_item',
            field=models.ManyToManyField(blank=True, to='master_table.FPItem'),
        ),
        migrations.AddField(
            model_name='report',
            name='lower_category_type',
            field=models.ManyToManyField(blank=True, to='master_table.FPLowerCat'),
        ),
        migrations.AddField(
            model_name='report',
            name='middle_category_type',
            field=models.ManyToManyField(blank=True, to='master_table.FPMiddleCat'),
        ),
        migrations.AlterField(
            model_name='report',
            name='customer',
            field=models.ManyToManyField(blank=True, to='master_table.Customer'),
        ),
    ]
