# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20170113_0522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='FundamentalProductType',
            new_name='fundamental_type',
        ),
    ]
