# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20161113_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedproductreport',
            name='fundamental_type',
            field=models.ManyToManyField(to='master_table.FundamentalProductType'),
        ),
        migrations.AlterField(
            model_name='finishedproductreport',
            name='middle_category_type',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, chained_field='fundamental_type', chained_model_field='fundamental_type', to='master_table.FPMiddleCat'),
        ),
    ]
