# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0067_auto_20170106_1325'),
        ('report', '0007_auto_20170113_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='deport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.Deport'),
        ),
    ]
