# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_report_deport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='fp_item',
            field=models.ManyToManyField(blank=True, to='master_table.FPItem', verbose_name='Finished Product'),
        ),
    ]
