# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_report_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='name',
        ),
    ]
