# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_remove_report_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
