# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 16:52
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0070_fpitem_unit_price'),
        ('report', '0016_auto_20170117_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='shift',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='fundamental_type', chained_model_field='fundamental_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.Shift'),
        ),
    ]
