# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0019_auto_20170117_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='raw_item_report_choices',
            field=models.CharField(blank=True, choices=[('mother_godown', 'Mother Godown Raw Item Stock Report'), ('production_godown', 'Factory Godown Raw Item Stock Report'), ('all', 'Total Raw Item Stock Report')], help_text='Select Report Category: ', max_length=30, null=True),
        ),
    ]
