# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0022_auto_20170126_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='deport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.Deport', to_field='code', verbose_name='Depot'),
        ),
    ]
