# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_table', '0004_auto_20161112_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
