# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0006_auto_20161121_1012'),
        ('production_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawItemEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_amount', models.FloatField()),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('edit_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fundamental_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.FundamentalProductType')),
                ('raw_item', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='fundamental_type', chained_model_field='fundamental_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.RawItem')),
            ],
            options={
                'verbose_name_plural': 'Production Godown Raw Items Entry',
                'verbose_name': 'Production Godown Raw Item Entry',
            },
        ),
    ]
