# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0008_compoundproductionitementry_unit_amount'),
        ('production_table', '0002_auto_20161016_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionentry',
            name='compound_production_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_table.CompoundProductionItem'),
            preserve_default=False,
        ),
    ]
