# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production_table', '0002_auto_20161215_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionentry',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='productionentry',
            name='edit_time',
        ),
        migrations.RemoveField(
            model_name='rawitementry',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='rawitementry',
            name='edit_time',
        ),
        migrations.RemoveField(
            model_name='riissueentry',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='riissueentry',
            name='edit_time',
        ),
        migrations.RemoveField(
            model_name='rireturnentry',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='rireturnentry',
            name='edit_time',
        ),
        migrations.AddField(
            model_name='productionentry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rawitementry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='riissueentry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rireturnentry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
