# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_table', '0003_auto_20170103_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionentry',
            name='unit_type',
            field=models.CharField(choices=[('kg', 'KG'), ('ton', 'TON')], default='kg', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawitementry',
            name='unit_type',
            field=models.CharField(choices=[('kg', 'KG'), ('ton', 'TON')], default='kg', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riissueentry',
            name='unit_type',
            field=models.CharField(choices=[('kg', 'KG'), ('ton', 'TON')], default='kg', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rireturnentry',
            name='unit_type',
            field=models.CharField(choices=[('kg', 'KG'), ('ton', 'TON')], default='kg', max_length=30),
            preserve_default=False,
        ),
    ]
