# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_table', '0003_riissueentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riissueentry',
            name='invoice_no',
        ),
    ]
