# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_table', '0003_productionentry_compound_production_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionentry',
            name='compound_production_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.CompoundProductionItem'),
        ),
        migrations.AlterField(
            model_name='productionentry',
            name='production_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.ProductionItem'),
        ),
    ]
