# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_table', '0004_auto_20161016_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionentry',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
