# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_table', '0004_auto_20170103_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionentry',
            name='enroll_comment_in_report',
            field=models.BooleanField(default=False, verbose_name='Enroll This Comment In Report:'),
        ),
        migrations.AddField(
            model_name='rawitementry',
            name='enroll_comment_in_report',
            field=models.BooleanField(default=False, verbose_name='Enroll This Comment In Report:'),
        ),
        migrations.AddField(
            model_name='riissueentry',
            name='enroll_comment_in_report',
            field=models.BooleanField(default=False, verbose_name='Enroll This Comment In Report:'),
        ),
        migrations.AddField(
            model_name='rireturnentry',
            name='enroll_comment_in_report',
            field=models.BooleanField(default=False, verbose_name='Enroll This Comment In Report:'),
        ),
    ]
