# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0007_auto_20161121_1100'),
        ('production_table', '0005_rireturnentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionentry',
            options={'verbose_name': 'Final Finished Product Entry', 'verbose_name_plural': 'Final Finished Product Entries'},
        ),
        migrations.RemoveField(
            model_name='productionentry',
            name='compound_production_item',
        ),
        migrations.RemoveField(
            model_name='productionentry',
            name='production_item',
        ),
        migrations.AddField(
            model_name='productionentry',
            name='finished_product_item',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='fundamental_type', chained_model_field='fundamental_type', default=1, on_delete=django.db.models.deletion.CASCADE, to='master_table.FinishedProductItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionentry',
            name='fundamental_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_table.FundamentalProductType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productionentry',
            name='shift',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='fundamental_type', chained_model_field='fundamental_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.Shift'),
        ),
    ]
