# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_table', '0006_auto_20161121_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionentry',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
