# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0011_remove_cpitem_type'),
        ('production_table', '0007_auto_20161121_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionentry',
            name='cp_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.CPItem'),
        ),
        migrations.AlterField(
            model_name='productionentry',
            name='finished_product_item',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='fundamental_type', chained_model_field='fundamental_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.FinishedProductItem'),
        ),
    ]
