# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0061_rawitem_grade'),
        ('production_table', '0009_auto_20170105_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionentry',
            name='finished_product_item',
        ),
        migrations.AddField(
            model_name='productionentry',
            name='fp_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.FPItem'),
        ),
        migrations.AddField(
            model_name='productionentry',
            name='fp_item_chained',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='lower_category_type', chained_model_field='lower_category_type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_entry_fp_chained', to='master_table.FPItem'),
        ),
        migrations.AddField(
            model_name='productionentry',
            name='fp_item_many',
            field=models.ManyToManyField(blank=True, null=True, related_name='p_entry_fp_many', to='master_table.FPItem'),
        ),
        migrations.AddField(
            model_name='productionentry',
            name='lower_category_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='middle_category_type', chained_model_field='middle_category_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.FPLowerCat'),
        ),
        migrations.AddField(
            model_name='productionentry',
            name='middle_category_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='fundamental_type', chained_model_field='fundamental_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.FPMiddleCat'),
        ),
    ]
