# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_table', '0010_auto_20170105_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionentry',
            name='fp_item_many',
            field=models.ManyToManyField(blank=True, related_name='p_entry_fp_many', to='master_table.FPItem'),
        ),
        migrations.AlterField(
            model_name='rawitementry',
            name='raw_item_many',
            field=models.ManyToManyField(blank=True, related_name='p_entry_ri_many', to='master_table.RawItem'),
        ),
        migrations.AlterField(
            model_name='riissueentry',
            name='raw_item_many',
            field=models.ManyToManyField(blank=True, related_name='p_ri_many', to='master_table.RawItem'),
        ),
        migrations.AlterField(
            model_name='rireturnentry',
            name='raw_item_many',
            field=models.ManyToManyField(blank=True, related_name='p_return_ri_many', to='master_table.RawItem'),
        ),
    ]
