# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, verbose_name='Expression')),
                ('action', models.CharField(choices=[('', '')], max_length=32)),
            ],
        ),
    ]
