# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_amount', models.FloatField()),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('edit_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fundamental_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.FundamentalProductType')),
                ('raw_item', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='fundamental_type', chained_model_field='fundamental_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.RawItem')),
            ],
            options={
                'verbose_name_plural': 'Main Godown To Production Godown Entry Table',
                'verbose_name': 'Main Godown To Production Godown Entry Table',
            },
        ),
        migrations.CreateModel(
            name='PurchaseEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField()),
                ('unit_amount', models.FloatField()),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('edit_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fundamental_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.FundamentalProductType')),
                ('raw_item', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='fundamental_type', chained_model_field='fundamental_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.RawItem')),
                ('suplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.Suplier')),
            ],
            options={
                'verbose_name_plural': 'New Purchase Entries To Mother Godown',
                'verbose_name': 'New Purchase Entry To Mother Godown',
            },
        ),
    ]
