# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mother_godown', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueentry',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='issueentry',
            name='edit_time',
        ),
        migrations.RemoveField(
            model_name='purchaseentry',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='purchaseentry',
            name='edit_time',
        ),
        migrations.AddField(
            model_name='issueentry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
