# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mother_godown', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issueentry',
            options={'verbose_name': 'Main Godown To Production Godown Entry Table', 'verbose_name_plural': 'Main Godown To Production Godown Entry Table'},
        ),
    ]
