# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mother_godown', '0002_auto_20161121_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseentry',
            options={'verbose_name': 'New Purchase Entry To Mother Godown', 'verbose_name_plural': 'New Purchase Entries To Mother Godown'},
        ),
    ]
