# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_godown', '0003_purchaseentry_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueentry',
            name='unit_type',
            field=models.CharField(choices=[('kg', 'KG'), ('ton', 'TON')], default='kg', max_length=30),
            preserve_default=False,
        ),
    ]
