# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_godown', '0003_auto_20161121_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseentry',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
