# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0006_auto_20161121_1012'),
        ('mother_godown', '0004_auto_20161121_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueentry',
            name='fundamental_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_table.FundamentalProductType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issueentry',
            name='raw_item',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='fundamental_type', chained_model_field='fundamental_type', on_delete=django.db.models.deletion.CASCADE, to='master_table.RawItem'),
        ),
    ]
