# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0039_remove_suplier_fundamental_type'),
        ('mother_godown', '0006_issueentry_enroll_comment_in_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueentry',
            name='enroll_comment_in_report',
        ),
        migrations.RemoveField(
            model_name='purchaseentry',
            name='suplier',
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_table.Supplier'),
            preserve_default=False,
        ),
    ]
