# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0043_auto_20170103_0857'),
        ('mother_godown', '0007_auto_20170103_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseentry',
            name='supplier',
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='supplier',
            field=models.ManyToManyField(to='master_table.Supplier'),
        ),
    ]
