# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_godown', '0008_auto_20170103_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseentry',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
