# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_godown', '0009_purchaseentry_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueentry',
            name='enroll_comment_in_report',
            field=models.BooleanField(default=False, verbose_name='Enroll This Comment In Report:'),
        ),
    ]
