# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mother_godown', '0012_auto_20170105_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueentry',
            name='fundamental_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.FundamentalProductType'),
        ),
    ]
