# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mother_godown', '0014_auto_20170105_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueentry',
            name='raw_item',
        ),
        migrations.RemoveField(
            model_name='issueentry',
            name='raw_item_chained',
        ),
    ]
