# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0061_rawitem_grade'),
        ('mother_godown', '0015_auto_20170105_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueentry',
            name='raw_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.RawItem'),
        ),
    ]
