# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 13:01
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0061_rawitem_grade'),
        ('mother_godown', '0016_issueentry_raw_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueentry',
            name='raw_item_chained',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='lower_category_type', chained_model_field='lower_category_type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_item_chained', to='master_table.RawItem'),
        ),
    ]
