# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0061_rawitem_grade'),
        ('mother_godown', '0017_issueentry_raw_item_chained'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseentry',
            name='lower_category_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='middle_category_type', chained_model_field='middle_category_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.RILowerCat'),
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='middle_category_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='fundamental_type', chained_model_field='fundamental_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.RIMiddleCat'),
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='raw_item_chained',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='lower_category_type', chained_model_field='lower_category_type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ri_chained', to='master_table.RawItem'),
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='raw_item_many',
            field=models.ManyToManyField(blank=True, null=True, related_name='ri_many', to='master_table.RawItem'),
        ),
        migrations.AlterField(
            model_name='purchaseentry',
            name='fundamental_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.FundamentalProductType'),
        ),
        migrations.AlterField(
            model_name='purchaseentry',
            name='raw_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_table.RawItem'),
        ),
    ]
