# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_godown', '0018_auto_20170105_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueentry',
            name='raw_item_many',
            field=models.ManyToManyField(blank=True, related_name='raw_item_many', to='master_table.RawItem'),
        ),
        migrations.AlterField(
            model_name='purchaseentry',
            name='raw_item_many',
            field=models.ManyToManyField(blank=True, related_name='ri_many', to='master_table.RawItem'),
        ),
    ]
